package com.yinhai.dbcatch.constant;

public interface DbInitSqlCost {
    String FIND_TABLE_SQL = "SELECT TABLENAME FROM SYS.SYSTABLES WHERE TABLETYPE='T' AND TABLENAME='%s'";
    //数据源表
    String CREATE_DS_SQL = "CREATE TABLE DBC_SOURCE_DATABASE ("
            + "ds_id int PRIMARY KEY generated by default as identity,"//自增主键
            + "ds_name VARCHAR(50) unique,"//数据源名称
            + "ds_type int,"//数据源类型
            + "ds_url VARCHAR(100),"//jdbc-url
            + "ds_username VARCHAR(100),"//
            + "ds_password VARCHAR(100),"//
            + "biz_user VARCHAR(50),"//j
            + "biz_time TIMESTAMP)";//创建时间

}
