package com.yinhai.dbcatch.constant;

public interface DbInitSqlCost {
    String FIND_TABLE_SQL = "SELECT TABLENAME FROM SYS.SYSTABLES WHERE TABLETYPE='T' AND TABLENAME='%s'";
    //数据源表
    String CREATE_DS_SQL = "CREATE TABLE DBC_SOURCE_DATABASE ("
            + "ds_id int PRIMARY KEY generated by default as identity,"//自增主键
            + "ds_name VARCHAR(50) unique,"//数据源名称
            + "ds_type int,"//数据源类型
            + "ds_url VARCHAR(100),"//jdbc-url
            + "ds_username VARCHAR(100),"//
            + "ds_password VARCHAR(100),"//
            + "biz_user VARCHAR(50),"//j
            + "biz_time TIMESTAMP)";//创建时间

    //采集任务表
    String CREATE_JOB_SQL = "CREATE TABLE DBC_EXTRACT_JOB ("
            + "job_id int PRIMARY KEY generated by default as identity,"//自增主键
            + "job_name VARCHAR(50) unique,"//任务名称
            + "job_state int,"//任务状态
            + "start_time TIMESTAMP,"//启动时间
            + "stop_time TIMESTAMP,"//停止时间
            + "run_log VARCHAR(1000),"//最新日志
            + "biz_user VARCHAR(50),"//j
            + "biz_time TIMESTAMP)";//更新时间

    //采集任务明细表
    String CREATE_JOB_DETAIL_SQL = "CREATE TABLE DBC_EXTRACT_JOB_DETAIL ("
            + "table_id int PRIMARY KEY generated by default as identity,"//自增主键,任务内表的ID
            + "table_name VARCHAR(50) ,"//表名称
            + "job_id int,"//所属的采集任务
            + "ds_id int,"//所属的数据源
            + "scn_num VARCHAR(100),"//当前的SCN号
            + "extract_num int,"//从启动到当前时间采集的数据量
            + "biz_user VARCHAR(50),"//j
            + "biz_time TIMESTAMP)";//更新时间

    //采集任务明细表
    String CREATE_TABLE_COL_SQL = "CREATE TABLE DBC_TABLE_COL ("
            + "col_id int PRIMARY KEY generated by default as identity,"//自增主键,任务内表的ID
            + "table_id int,"//所属的表
            + "col_name VARCHAR(100),"//字段名
            + "col_memo VARCHAR(100),"//字段备注
            + "order_num int,"//字段顺序
            + "biz_user VARCHAR(50),"//j
            + "biz_time TIMESTAMP)";//更新时间


}
